version: '3.8'
services:
  web:
    build: .
    ports:
      - '3000:3000'
    environment:
      # Configura la conexión a PostgreSQL
      DATABASE_URL: postgres://user:password@db:5432/dbname
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
