-- CreateEnum
CREATE TYPE "RoomStatus" AS ENUM ('LIBRE', 'RESERVADA', 'SUCIA', 'BLOQUEADA', 'OCUPADA', 'EN_MANTENIMIENTO', 'SUCIA_RESERVADA', 'SUCIA_OCUPADA', 'SUCIA_BLOQUEADA', 'LIMPIEZA', 'INSPECCION');

-- AlterTable
ALTER TABLE "Room" ADD COLUMN     "status" "RoomStatus" NOT NULL DEFAULT 'LIBRE';
